/*
 * Copyright (c) 2000 - 2014 Samsung Electronics Co., Ltd. All rights reserved.
 * Inha Song <ideal.song@samsung.com>
 *
 * See file CREDITS for list of people who contributed to this
 * project.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License as
 * published by the Free Software Foundation; either version 2 of
 * the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston,
 * MA 02111-1307 USA
 */

#ifndef __TIZEN_GPT_VER13_H__
#define __TIZEN_GPT_VER13_H__

#include <mobile/pit.h>

#define DEFAULT_PIT_NUM		29

static struct pit_info default_pit13 = {
	.hdr = {
		.magic = PIT_MAGIC,
		.count = DEFAULT_PIT_NUM,
		.gang_format = {'C', 'O', 'M', '_', 'T', 'A', 'R', '2'},
		.model = {'T', 'I', 'Z', 'E', 'N'},
		.dummy = {'V', '0', '1', '3'},
	},
	.entry[0] = {
		.bin_type	= PIT_BINTYPE_AP,
		.dev_type	= PIT_DEVTYPE_MMC,
		.id		= 80,
		.part_type	= PART_TYPE_BOOTLOADER,
		.filesys	= PART_FS_TYPE_BASIC,
		.blk_start	= 0,
		.blk_num	= 568,
		.offset		= 0,
		.file_size	= 0,
		.name		= "s-boot-mmc",
		.file_name	= "s-boot-mmc.bin",
		.delta_name	= "",
	},
	.entry[1] = {
		.bin_type	= PIT_BINTYPE_AP,
		.dev_type	= PIT_DEVTYPE_FILE,
		.id		= 81,
		.part_type	= PART_TYPE_DATA,
		.filesys	= PART_FS_TYPE_BASIC,
		.blk_start	= 568,
		.blk_num	= 312,
		.offset		= 0,
		.file_size	= 0,
		.name		= "tzsw",
		.file_name	= "tz.img",
		.delta_name	= "",
	},
	.entry[2] = {
		.bin_type	= PIT_BINTYPE_AP,
		.dev_type	= PIT_DEVTYPE_MMC,
		.id		= 70,
		.part_type	= PART_TYPE_DATA,
		.filesys	= PART_FS_TYPE_BASIC,
		.blk_start	= 64,
		.blk_num	= 16,
		.offset		= 0,
		.file_size	= 0,
		.name		= "pit",
		.file_name	= "Tizen_GPT_Ver13.pit",
		.delta_name	= "",
	},
	.entry[3] = {
		.bin_type	= PIT_BINTYPE_AP,
		.dev_type	= PIT_DEVTYPE_MMC,
		.id		= 71,
		.part_type	= PART_TYPE_DATA,
		.filesys	= PART_FS_TYPE_BASIC,
		.blk_start	= 4224,
		.blk_num	= 2048,
		.offset		= 0,
		.file_size	= 0,
		.name		= "MD5HDR",
		.file_name	= "md5.img",
		.delta_name	= "",
	},
	.entry[4] = {
		.bin_type	= PIT_BINTYPE_AP,
		.dev_type	= PIT_DEVTYPE_MMC,
		.id		= 1,
		.part_type	= PART_TYPE_DATA,
		.filesys	= PART_FS_TYPE_BASIC,
		.blk_start	= 128,
		.blk_num	= 2048,
		.offset		= 0,
		.file_size	= 0,
		.name		= "u-boot-mmc",
		.file_name	= "u-boot-mmc.bin",
		.delta_name	= "",
	},
	.entry[5] = {
		.bin_type	= PIT_BINTYPE_AP,
		.dev_type	= PIT_DEVTYPE_MMC,
		.id		= 2,
		.part_type	= PART_TYPE_DATA,
		.filesys	= PART_FS_TYPE_BASIC,
		.blk_start	= 2176,
		.blk_num	= 2048,
		.offset		= 0,
		.file_size	= 0,
		.name		= "u-boot-mmc-bak",
		.file_name	= "u-boot-mmc.bin",
		.delta_name	= "",
	},
	.entry[6] = {
		.bin_type	= PIT_BINTYPE_AP,
		.dev_type	= PIT_DEVTYPE_MMC,
		.id		= 3,
		.part_type	= PART_TYPE_DATA,
		.filesys	= PART_FS_TYPE_BASIC,
		.blk_start	= 6272,
		.blk_num	= 512,
		.offset		= 0,
		.file_size	= 0,
		.name		= "params",
		.file_name	= "params.bin",
		.delta_name	= "",
	},
	.entry[7] = {
		.bin_type	= PIT_BINTYPE_AP,
		.dev_type	= PIT_DEVTYPE_MMC,
		.id		= 4,
		.part_type	= PART_TYPE_DATA,
		.filesys	= PART_FS_TYPE_BASIC,
		.blk_start	= 6784,
		.blk_num	= 2048,
		.offset		= 0,
		.file_size	= 0,
		.name		= "log",
		.file_name	= "log",
		.delta_name	= "",
	},
	.entry[8] = {
		.bin_type	= PIT_BINTYPE_AP,
		.dev_type	= PIT_DEVTYPE_MMC,
		.id		= 5,
		.part_type	= PART_TYPE_DATA,
		.filesys	= PART_FS_TYPE_BASIC,
		.blk_start	= 8832,
		.blk_num	= 99712,
		.offset		= 0,
		.file_size	= 0,
		.name		= "reserved",
		.file_name	= "reserved",
		.delta_name	= "",
	},
	.entry[9] = {
		.bin_type	= PIT_BINTYPE_AP,
		.dev_type	= PIT_DEVTYPE_MMC,
		.id		= 6,
		.part_type	= PART_TYPE_DATA,
		.filesys	= PART_FS_TYPE_EXT4,
		.blk_start	= 24576,
		.blk_num	= 40960,
		.offset		= 0,
		.file_size	= 0,
		.name		= "EFS",
		.file_name	= "efs.img",
		.delta_name	= "",
	},
	.entry[10] = {
		.bin_type	= PIT_BINTYPE_AP,
		.dev_type	= PIT_DEVTYPE_MMC,
		.id		= 7,
		.part_type	= PART_TYPE_DATA,
		.filesys	= PART_FS_TYPE_EXT4,
		.blk_start	= 65536,
		.blk_num	= 28672,
		.offset		= 0,
		.file_size	= 0,
		.name		= "boot",
		.file_name	= "boot.img",
		.delta_name	= "",
	},
	.entry[11] = {
		.bin_type	= PIT_BINTYPE_AP,
		.dev_type	= PIT_DEVTYPE_MMC,
		.id		= 8,
		.part_type	= PART_TYPE_DATA,
		.filesys	= PART_FS_TYPE_EXT4,
		.blk_start	= 94208,
		.blk_num	= 75776,
		.offset		= 0,
		.file_size	= 0,
		.name		= "recovery",
		.file_name	= "recovery.img",
		.delta_name	= "",
	},
	.entry[12] = {
		.bin_type	= PIT_BINTYPE_AP,
		.dev_type	= PIT_DEVTYPE_MMC,
		.id		= 9,
		.part_type	= PART_TYPE_DATA,
		.filesys	= PART_FS_TYPE_EXT4,
		.blk_start	= 169984,
		.blk_num	= 28672,
		.offset		= 0,
		.file_size	= 0,
		.name		= "csa",
		.file_name	= "csa-mmc",
		.delta_name	= "",
	},
	.entry[13] = {
		.bin_type	= PIT_BINTYPE_AP,
		.dev_type	= PIT_DEVTYPE_MMC,
		.id		= 10,
		.part_type	= PART_TYPE_DATA,
		.filesys	= PART_FS_TYPE_EXT4,
		.blk_start	= 198656,
		.blk_num	= 176128,
		.offset		= 0,
		.file_size	= 0,
		.name		= "modem",
		.file_name	= "modem.img",
		.delta_name	= "",
	},
	.entry[14] = {
		.bin_type	= PIT_BINTYPE_AP,
		.dev_type	= PIT_DEVTYPE_MMC,
		.id		= 11,
		.part_type	= PART_TYPE_DATA,
		.filesys	= PART_FS_TYPE_EXT4,
		.blk_start	= 374784,
		.blk_num	= 28672,
		.offset		= 0,
		.file_size	= 0,
		.name		= "reserved3",
		.file_name	= "reserved3",
		.delta_name	= "",
	},
	.entry[15] = {
		.bin_type	= PIT_BINTYPE_AP,
		.dev_type	= PIT_DEVTYPE_MMC,
		.id		= 12,
		.part_type	= PART_TYPE_DATA,
		.filesys	= PART_FS_TYPE_EXT4,
		.blk_start	= 403456,
		.blk_num	= 40960,
		.offset		= 0,
		.file_size	= 0,
		.name		= "ramdisk1",
		.file_name	= "ramdisk.img",
		.delta_name	= "",
	},
	.entry[16] = {
		.bin_type	= PIT_BINTYPE_AP,
		.dev_type	= PIT_DEVTYPE_MMC,
		.id		= 13,
		.part_type	= PART_TYPE_DATA,
		.filesys	= PART_FS_TYPE_EXT4,
		.blk_start	= 444416,
		.blk_num	= 40960,
		.offset		= 0,
		.file_size	= 0,
		.name		= "ramdisk2",
		.file_name	= "ramdisk-recovery.img",
		.delta_name	= "",
	},
	.entry[17] = {
		.bin_type	= PIT_BINTYPE_AP,
		.dev_type	= PIT_DEVTYPE_MMC,
		.id		= 14,
		.part_type	= PART_TYPE_DATA,
		.filesys	= PART_FS_TYPE_EXT4,
		.blk_start	= 485376,
		.blk_num	= 40960,
		.offset		= 0,
		.file_size	= 0,
		.name		= "module",
		.file_name	= "modules.img",
		.delta_name	= "",
	},
	.entry[18] = {
		.bin_type	= PIT_BINTYPE_AP,
		.dev_type	= PIT_DEVTYPE_MMC,
		.id		= 15,
		.part_type	= PART_TYPE_DATA,
		.filesys	= PART_FS_TYPE_EXT4,
		.blk_start	= 526336,
		.blk_num	= 20480,
		.offset		= 0,
		.file_size	= 0,
		.name		= "fota",
		.file_name	= "fota",
		.delta_name	= "",
	},
	.entry[19] = {
		.bin_type	= PIT_BINTYPE_AP,
		.dev_type	= PIT_DEVTYPE_MMC,
		.id		= 16,
		.part_type	= PART_TYPE_DATA,
		.filesys	= PART_FS_TYPE_EXT4,
		.blk_start	= 546816,
		.blk_num	= 6144000,
		.offset		= 0,
		.file_size	= 0,
		.name		= "rootfs",
		.file_name	= "rootfs.img",
		.delta_name	= "",
	},
	.entry[20] = {
		.bin_type	= PIT_BINTYPE_AP,
		.dev_type	= PIT_DEVTYPE_MMC,
		.id		= 17,
		.part_type	= PART_TYPE_DATA,
		.filesys	= PART_FS_TYPE_EXT4,
		.blk_start	= 6690816,
		.blk_num	= 1048576,
		.offset		= 0,
		.file_size	= 0,
		.name		= "system-data",
		.file_name	= "system-data.img",
		.delta_name	= "",
	},
	.entry[21] = {
		.bin_type	= PIT_BINTYPE_AP,
		.dev_type	= PIT_DEVTYPE_MMC,
		.id		= 18,
		.part_type	= PART_TYPE_DATA,
		.filesys	= PART_FS_TYPE_EXT4,
		.blk_start	= 7739392,
		.blk_num	= 307200,
		.offset		= 0,
		.file_size	= 0,
		.name		= "csc",
		.file_name	= "csc.img",
		.delta_name	= "",
	},
	.entry[22] = {
		.bin_type	= PIT_BINTYPE_AP,
		.dev_type	= PIT_DEVTYPE_MMC,
		.id		= 19,
		.part_type	= PART_TYPE_DATA,
		.filesys	= PART_FS_TYPE_EXT4,
		.blk_start	= 8046592,
		.blk_num	= 0,
		.offset		= 0,
		.file_size	= 0,
		.name		= "user",
		.file_name	= "user.img",
		.delta_name	= "remained",
	},
	.entry[23] = {
		.bin_type	= PIT_BINTYPE_AP,
		.dev_type	= PIT_DEVTYPE_FILE,
		.id		= 20,
		.part_type	= PART_TYPE_DATA,
		.filesys	= PART_FS_TYPE_EXT4,
		.blk_start	= 0,
		.blk_num	= 14336,
		.offset		= 0,
		.file_size	= 0,
		.name		= "kernel",
		.file_name	= "uImage",
		.delta_name	= "",
	},
	.entry[24] = {
		.bin_type	= PIT_BINTYPE_AP,
		.dev_type	= PIT_DEVTYPE_FILE,
		.id		= 21,
		.part_type	= PART_TYPE_DATA,
		.filesys	= PART_FS_TYPE_EXT4,
		.blk_start	= 0,
		.blk_num	= 24576,
		.offset		= 0,
		.file_size	= 0,
		.name		= "modem_bin",
		.file_name	= "modem.bin",
		.delta_name	= "",
	},
	.entry[25] = {
		.bin_type	= PIT_BINTYPE_AP,
		.dev_type	= PIT_DEVTYPE_FILE,
		.id		= 22,
		.part_type	= PART_TYPE_DATA,
		.filesys	= PART_FS_TYPE_EXT4,
		.blk_start	= 0,
		.blk_num	= 24567,
		.offset		= 0,
		.file_size	= 0,
		.name		= "modem_cdma",
		.file_name	= "modem_cdma.bin",
		.delta_name	= "",
	},
	.entry[26] = {
		.bin_type	= PIT_BINTYPE_AP,
		.dev_type	= PIT_DEVTYPE_FILE,
		.id		= 23,
		.part_type	= PART_TYPE_DATA,
		.filesys	= PART_FS_TYPE_EXT4,
		.blk_start	= 0,
		.blk_num	= 245760,
		.offset		= 0,
		.file_size	= 0,
		.name		= "install-patch",
		.file_name	= "install-patch_1.deb",
		.delta_name	= "",
	},
	.entry[27] = {
		.bin_type	= PIT_BINTYPE_AP,
		.dev_type	= PIT_DEVTYPE_FILE,
		.id		= 24,
		.part_type	= PART_TYPE_DATA,
		.filesys	= PART_FS_TYPE_EXT4,
		.blk_start	= 0,
		.blk_num	= 24567,
		.offset		= 0,
		.file_size	= 0,
		.name		= "fdt",
		.file_name	= "slp.dtb",
		.delta_name	= "",
	},
	.entry[28] = {
		.bin_type	= PIT_BINTYPE_AP,
		.dev_type	= PIT_DEVTYPE_FILE,
		.id		= 25,
		.part_type	= PART_TYPE_DATA,
		.filesys	= PART_FS_TYPE_EXT4,
		.blk_start	= 0,
		.blk_num	= 245760,
		.offset		= 0,
		.file_size	= 0,
		.name		= "rw-update",
		.file_name	= "rw_update.tar",
		.delta_name	= "",
	},
};

#endif
